### ISSUE TITLE
[feature/manager] #2 관리자 여러 페이지 추가 

### ISSUE THREAD

**Issue by syongsyong6035** [springTeamm/smile-front#2]
## 💭 작업 브랜치
> [feature/manager]

## 🍀 기능 설명
> 동아리 관리 페이지 및 공간 관리 페이지 및 예약 관리 페이지 및 판매자 정보 페이지 및 취소페이지 추가
>공통으로 들어가는 컴포넌트 ui구성

## 🎀 작업 상세 내용
- [ ] TODO 관리자페이지관련되어있는 프론트 구성했습니다 

## 📈 기타
> 리뷰 월별 관리 매출은 아직 하지 못했습니다
>검색 컴포넌트가 전체적으로 너무 많이 바뀌어서 어떻게 할지 고민중이지만 전체적인 틀은 잡아놧습니다

**Comment by k168ww** [comment]
관리자 이미 진행하고 있는 것 같아서...
이슈가 현재 구두식으로 작성되어 있으니 다른 이슈들 보고 조금 더 문서화하여 이슈 수정 부탁드립니다.

**Comment by syongsyong6035** [comment]
넵 알겠습니다
